"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import store from "./store/store";
const inter = Inter({ subsets: ["latin"] });
// import favicon from "../../public/assets/sneakers.png"

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (

    <html lang="en" className="scroll_frezz">
      <head>
        <link rel="icon"  href="/favicon.ico" />

      </head>
      <Provider store={store}>
        <body className={inter.className}>{children}</body>
      </Provider>
    </html >

  );
}
